jobs:
  - name: set-secrets
    plan:
      - task: set-secrets
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gcr.io/cloud-builders/kubectl
          params:
            SERVICE_ACCOUNT_JSON: ((gcp.service_account_json))
            TEAM_NAME: ((team_name))
            KMS_SECRET: ((base64_secret))
            GROUP: ((group))
          run:
            path: /bin/bash
            args:
              - -ce
              - |-
                cat >~/gcloud-service-key.json <<EOL
                $SERVICE_ACCOUNT_JSON
                EOL

                gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
                gcloud container clusters get-credentials k8s-ci --zone europe-west2 --project ons-ci --internal-ip

                echo -n ${KMS_SECRET} | base64 -d | gcloud kms decrypt --project ons-ci --location europe-west2 --keyring concourse --key ${TEAM_NAME} --plaintext-file secrets --ciphertext-file '-'
                kubectl create secret generic ${GROUP} -n "concourse-es-take-on" --from-env-file=./secrets --dry-run -o yaml | kubectl apply -f -
                kubectl get secret aws -o yaml -n "concourse-es-take-on"